# Generated by Django 6.0.1 on 2026-01-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
